Carousel/urls.py
from django.conf.urls import include, url
from . import views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'VideoListWS', views.VideoList, {'sports_name','sports_subtype'})
router.register(r'SportSubtypeWS', views.SportSubtype,{'sports_name'})

urlpatterns =  [
    url(r'^', include(router.urls)),
]

djangocmssite/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals

from cms.sitemaps import CMSSitemap
from rest_framework import routers
from django.conf import settings
from django.conf.urls import *  # NOQA
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from players import views as playersviews
#from adminlogin import views as loginadmin
from restapp import views
from sportsadmin import views as sportsadmin
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static


admin.autodiscover()

urlpatterns = i18n_patterns('',
    url(r'^admin/', include(admin.site.urls)),  # NOQA
    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap',
        {'sitemaps': {'cmspages': CMSSitemap}}),
    url(r'^select2/', include('django_select2.urls')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^newsfeature/', include('aldryn_newsblog.urls', namespace='newsblog')),
    url(r'^testWS/$', views.Album.as_view()),
    url(r'^playersList/$',playersviews.getPlayersListData),
    url(r'^asset/', include('assetManagement.urls')),
    url(r'^carousel/', include('Carousel.urls')),
    url(r'^sports/', include('sportsList.urls')),
    url(r'^training/', include('Training.urls')),
    #url(r'^adminlogin/', loginadmin.loginadmin),
    url(r'^sportsadmin/', include('sportsadmin.urls')),
    url(r'^listCoach/$',sportsadmin.CoachList),
    url(r'^listAcademy/$',sportsadmin.AcademyList),
    url(r'^listPlayer/$',sportsadmin.PlayerList),
    url(r'^listVideo/$',sportsadmin.VideoList),
    url(r'^listPicture/$',sportsadmin.PictureList,name="listPicture"),
    url(r'^addPlayer/', sportsadmin.addPlayer , name ="addPlayer"),
    url(r'^addVideo/', sportsadmin.addVideo,name ="addVideo"),
    #url(r'^addPhoto/', sportsadmin.addPhoto),
    # vaibhav added
    url(r'^advanceSearch/', sportsadmin.advanceSearch),
    url(r'^loginAdmin/', sportsadmin.sportsAdminLogin),
    url(r'^logoutAdmin/', sportsadmin.adminLogout,name="logout"),
    url(r'^loginAuthentication/', sportsadmin.adminAuthenticate,name="loginSports"),
	# end vaibhav url
    url(r'^sportsadmin/', sportsadmin.addPhoto,name="add"),
    url(r'^deletePlayer/(?:playerId=(?P<playerId>\d+)/)?$', sportsadmin.deletePlayer),
    url(r'^deleteCoach/(?:coachId=(?P<coachId>\d+)/)?$', sportsadmin.deleteCoach),
    url(r'^deleteVideo/(?:videoId=(?P<videoId>\d+)/)?$', sportsadmin.deleteVideo),
    url(r'^deletePhoto/(?:pictureId=(?P<pictureId>\d+)/)?$', sportsadmin.deletePhoto),
    url(r'^deleteAcademy/(?:academyId=(?P<academyId>\d+)/)?$', sportsadmin.deleteAcademy),
    url(r'^viewPlayer/(?:playerId=(?P<playerId>\d+)/)?$',sportsadmin.viewPlayer),
    url(r'^viewCoach/(?:coachId=(?P<coachId>\d+)/)?$',sportsadmin.viewCoach),
    url(r'^viewPhoto/(?:pictureId=(?P<pictureId>\d+)/)?$',sportsadmin.viewPhoto),
    url(r'^viewAcademy/(?:academyId=(?P<academyId>\d+)/)?$',sportsadmin.viewAcademy),
    url(r'^viewVideo/(?:videoId=(?P<videoId>\d+)/)?$',sportsadmin.viewVideo),
    url(r'^addCoach/', sportsadmin.addCoach , name ="addCoach"),
    url(r'^addAcademy/', sportsadmin.addAcademy , name ="addAcademy"),
    url(r'^editAcademy/', sportsadmin.editAcademy , name ="editAcademy"),
	url(r'^', include('cms.urls')),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
			url(r'', include('django.contrib.staticfiles.urls'))
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

polls/urls.py
#-*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from . import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

sportsadmin/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns =  [ 
    url(r'^$', views.homePge),
]

sportsadmin/models.py
from django.db import models

# Create your models here.

sportsadmin/forms.py
from django import forms
#from material import *
from sportsList.models import *
#from cProfile import label
from django.forms.models import inlineformset_factory
from Carousel.models import *
from django.forms import fields

class loginForm(forms.Form):
    username = forms.CharField(required=True,widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password = forms.CharField(required=True,widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))

    

    
class AddressForm(forms.ModelForm):
    country=forms.ModelChoiceField(queryset=Country.objects.all(),required=False,help_text="Select Country",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    province=forms.ModelChoiceField(queryset=Province.objects.all(),required=False,help_text="Select Province",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    city=forms.ModelChoiceField(queryset=City.objects.all(),required=False,help_text="Select City",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    street1=forms.CharField(max_length=30,required=False, help_text="Street1",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Street1','maxlength':'30','required':'False'}))
    street2=forms.CharField(max_length=30,required=False, help_text=" Street2",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Street2','maxlength':'30','required':'False'}))
    zipcode=forms.IntegerField(required=False,help_text="Zipcode",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Zipcode','maxlength':'6','required':'False'}))
    
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Address
        fields = ('country', 'province','city','street1','street2','zipcode')


class PlayerOnBoardingForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','maxlength':'50','placeholder':'First Name','required':'False'}))
    middle_name=forms.CharField(label="Middle Name",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Middle Name','maxlength':'50','required':'False'}))
    last_name=forms.CharField(label="Last Name",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Last Name','maxlength':'50','required':'False'}))
    gender=forms.ModelChoiceField(queryset=Gender.objects.all(),required=False,widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
	#gender=forms.ChoiceField(choices=((None, ''), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')),widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    date_of_birth = forms.DateField(required=False,widget=forms.DateInput(attrs={'class':'form-control col-sm-3 date','placeholder':'yyyy-mm-dd', 'type':'date','data-fv-date':'true','data-fv-date-format':'YYYY/MM/DD','data-fv-date-message':'The value is not a valid date'}))
    email_id=forms.CharField(label="Email Id",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Email ID','maxlength':'100','required':'False'}))
    contact_no=forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Contact No','maxlength':'12','required':'False'}))
    sports=forms.ModelChoiceField(queryset=Sports.objects.all(),required=False,label="Sport",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    total_yrs_exp=forms.IntegerField(required=False,label="Total Yrs Experiance",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Total Yrs Experiance','maxlength':'2','required':'False'}))
    sec_ques=forms.ModelChoiceField(required=False,queryset=SecurityQuestions.objects.all(),label="Security question 1",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    sec_ans1=forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Sequrity Answer','maxlength':'100','required':'False'}))
    address = forms.IntegerField(required=False)
    acd_reg = forms.ModelChoiceField(queryset=AcademyOnboarding.objects.all(),required=False,label="Enter Academy" ,widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    

    class Meta:
       
        model = PlayerOnboarding
        fields = ('first_name', 'middle_name','last_name','gender','email_id','contact_no','date_of_birth','sports','total_yrs_exp','sec_ques','sec_ans1','address','acd_reg')

		
class CoachOnBoardingForm(forms.ModelForm):
    first_name = forms.CharField(label="First Name",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','maxlength':'50','placeholder':'First Name','required':'False'}))
    middle_name=forms.CharField(label="Middle Name",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Middle Name','maxlength':'50','required':'False'}))
    last_name=forms.CharField(label="Last Name",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Last Name','maxlength':'50','required':'False'}))
    gender=forms.ModelChoiceField(queryset=Gender.objects.all(),required=False,widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
	#gender=forms.ChoiceField(choices=((None, ''), ('F', 'Female'), ('M', 'Male'), ('O', 'Other')),widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    date_of_birth = forms.DateField(required=False,widget=forms.DateInput(attrs={'class':'form-control col-sm-3 date','placeholder':'yyyy-mm-dd', 'type':'date','data-fv-date':'true','data-fv-date-format':'YYYY/MM/DD','data-fv-date-message':'The value is not a valid date'}))
    email_id=forms.CharField(label="Email Id",required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Email ID','maxlength':'100','required':'False'}))
    contact_no=forms.IntegerField(required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Contact No','maxlength':'12','required':'False'}))
    sports=forms.ModelChoiceField(required=False,queryset=Sports.objects.all(),label="Sport",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    total_yrs_exp=forms.IntegerField(required=False,label="Total Yrs Experiance",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Total Yrs Experiance','maxlength':'2','required':'False'}))
    sec_ques=forms.ModelChoiceField(required=False,queryset=SecurityQuestions.objects.all(),label="Security question 1",widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    sec_ans1=forms.CharField(required=False,widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Sequrity Answer','maxlength':'100','required':'False'}))
    address = forms.IntegerField(required=False)
    acd_reg = forms.ModelChoiceField(queryset=AcademyOnboarding.objects.all(),required=False,label="Enter Academy" ,widget=forms.Select(attrs={'class':'form-control col-sm-3'}))
    

    class Meta:
        # Provide an association between the ModelForm and a model
        model = CoachOnboarding
        fields = ('first_name', 'middle_name','last_name','gender','date_of_birth','email_id','contact_no','sports','total_yrs_exp','sec_ques','sec_ans1','address','acd_reg')

		
		
class AcademyOnboardingForm(forms.ModelForm):
    acd_reg=forms.CharField( required = False,widget=forms.HiddenInput())
    name = forms.CharField(label="Name",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Name','maxlength':'100','required':'False'})) 
    estd = forms.DateField(widget=forms.DateInput(attrs={'class':'form-control col-sm-3 date','placeholder':'yyyy-mm-dd', 'type':'date','data-fv-date':'true','data-fv-date-format':'YYYY/MM/DD','data-fv-date-message':'The value is not a valid date'}))
    email_id=forms.CharField(label="Email Id",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Email Id','maxlength':'100','required':'False'}))
    contact_no=forms.IntegerField(help_text="Enter Contact No",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Contact No','maxlength':'12','required':'False'}))
    website = forms.CharField(label="Website",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Website','maxlength':'50','required':'False'}))
    address = forms.CharField( required = False,widget=forms.HiddenInput())
    
    class Meta:
        # Provide an association between the ModelForm and a model
        model = AcademyOnboarding
        fields = ('name', 'estd','website','contact_no', 'email_id')
		
class CarouselVideoForm(forms.ModelForm):   
    movie_url=forms.CharField(label="Movie url",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Movie url','maxlength':'255','required':'True'}))  
    width=forms.IntegerField(help_text="Width",label="Width",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Width','required':'False'}))
    height=forms.IntegerField(help_text="Height",label="Height",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'Height','required':'False'}))
    auto_play = forms.BooleanField(required=False,label="Auto Play")
    auto_hide = forms.BooleanField(required=False,label="Auto Hide")
    fullscreen = forms.BooleanField(required=False,label="Fullscreen")
    loop=forms.BooleanField(required=False,label="Loop")
    bgcolor=forms.CharField(label="bgcolor",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'000000','maxlength':'6','required':'False'}))
    textcolor=forms.CharField(initial="FFFFFF",label="textcolor",widget=forms.TextInput(attrs={'class':'form-control col-sm-3','placeholder':'FFFFFF','maxlength':'6','required':'False'}))

sportsadmin/templates/sportsadmin/CoachList.html
	{% load table_tags %}
	{% load staticfiles %}
<link href="{% static 'sportsadmin/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css"> -->
<script src="{% static 'sportsadmin/js/jquery-2.1.4.min.js' %}"></script> 
<script src="{% static 'sportsadmin/js/bootstrap.min.js' %}"></script>
<script src="{% static 'sportsadmin/js/commonUtils.js' %}"></script>

        

<style type="text/css">

 .modal.modal-wide .modal-dialog {
  width: 80%;
}
.modal-wide .modal-body {
  overflow-y: auto;
}
</style>

<script>
$(document).ready(function(){
	$(".fa-trash-o").on("click", function() {	
		coachId = $(this).closest('tr').find('td:eq(0)').html();
		$("#yesDelCoach").on("click", function(){
			var url = '/deleteCoach/'+'?coachId='+coachId;
		 	$.ajax({
				url : url,
				type : "GET",
				dataType : {},}) 
			    .done(function(data) {
			    	console.log("after delete");			    	
			});
		});
	  });
	  
	  $('.fa-edit').on("click",function(){
		console.log("hit edit");
		$('#addCoachModal').modal('show'); 
		coachId = $(this).closest('tr').find('td:eq(0)').html();
		var url= '/viewCoach/'+'?coachId='+coachId;
		CoachViewEdit(url);
		$('#action_type').val("edit");
		
	});
	 
	 $(".fa-file-text").on("click", function() {
		console.log("hit view");
		$('#addCoachModal').modal('show'); 	
		coachId = $(this).closest('tr').find('td:eq(0)').html();
		var url= '/viewCoach/'+'?coachId='+coachId;
		CoachViewEdit(url);
		viewOnlyAccess();
		
	});
	 
	 $('#addCoachModal').on('hidden.bs.modal', function () {
		   tab_handler('Coach');
	});
	 $('#deleteCoachModal').on('hidden.bs.modal', function () {
		   tab_handler('Coach');
	}); 
	
});

function viewOnlyAccess()
{
	$('#id_first_name').prop("disabled", true);
	$('#id_middle_name').prop("disabled", true);
	$('#id_last_name').prop("disabled", true);
	$('#id_email_id').prop("disabled", true);
	$('#id_contact_no').prop("disabled", true);
	$('#id_total_yrs_exp').prop("disabled", true);
	$('#id_sec_ans1').prop("disabled", true);
	$('#id_date_of_birth').prop("disabled", true);
	$('#id_street1').prop("disabled", true);
	$('#id_street2').prop("disabled", true);
	$('#id_zipcode').prop("disabled", true);
	$('#id_city').prop("disabled", true);
	$('#id_province').prop("disabled", true);
	$('#id_country').prop("disabled", true);
	$('#id_gender').prop("disabled", true);
	$('#id_sports').prop("disabled", true);
	$('#id_sec_ques').prop("disabled", true);
	$('#id_acd_reg').prop("disabled", true);
}

function CoachViewEdit(url)
{
	$
	.ajax({
		url : url,
		type : "GET",
		dataType : 'json',}) 
		.done(function(data) {
				    console.log(data.coach.coach_id);
	          		$('#coach_id').val(data.coach.coach_id);   	
       				$('#address_id').val(data.address.address_id);   
	          		$('#id_first_name').val(data.coach.first_name);
	          		$('#id_middle_name').val(data.coach.middle_name);	          		
	          		$('#id_last_name').val(data.coach.last_name);	          		
	          		$('#id_email_id').val(data.coach.email_id);	          		
	          		$('#id_contact_no').val(data.coach.contact_no);	          		
	          		$('#id_total_yrs_exp').val(data.coach.total_yrs_exp);	          		
	          		$('#id_date_of_birth').val(data.coach.date_of_birth);	          		
	          		$('#id_sec_ans1').val(data.coach.sec_ans1);	          			          		
	          		          			          		
	          		/* Player Address */
                    console.log(data.address.address_id)					
	          		$('#id_street1').val(data.address.street1);	          			          		
	          		$('#id_street2').val(data.address.street2);	          			          		
	          		$('#id_zipcode').val(data.address.zipcode);	          			          		
	          		
	          		
	          		$('#id_city').append('<option selected=selected  value=' + data.city.city_id + '>'+data.city.city_name+'</option>');
	          		$('#id_province').append('<option selected=selected value=' + data.province.province_id + '>'+data.province.province_name+'</option>');
	          		$('#id_country').append('<option selected=selected value=' + data.country.country_id + '>'+data.country.country_name+'</option>');
	          	  	//dropdowns within coach form
	          		$('#id_gender').append('<option selected=selected  value=' + data.genderVal.gender_id + '>'+data.genderVal.gender+'</option>');
	          		$('#id_sports').append('<option selected=selected value=' + data.sports.sports_id + '>'+data.sports.sports_name+'</option>');
	          		$('#id_sec_ques').append('<option selected=selected value=' + data.sec_ques1.sec_ques_id + '>'+data.sec_ques1.sec_ques+'</option>');
					$('#id_acd_reg').append('<option selected=selected  value=' + data.academy.acd_reg_id + '>'+data.academy.name+'</option>');			
	
		});
	
}

$('#saveStudBtn').on("click" , function(){

// catch the form's submit event
            $.ajax({ // create an AJAX call...
                data: $('#Coach').serialize(), // get the form data
                type: "POST", // GET or POST
                url: $('#Coach').attr('action'), // the file to call
                success: function(response) { // on success..
                    // update the DIV
                },
				error: function(response){
				
				}
            });	
});



</script>
<div class="col-md-3 col-sm-6 col-xs-12" style="float: right;width:30%"
 data-toggle="modal" data-target="#addCoachModal">
 <div class="info-box">
  <span class="info-box-icon bg-green"><i
   class="fa fa-plus-circle"></i></span>
		
  <div class="info-box-content" id="addCoach" style="padding: 34px 58px; margin-left: 70px;width: 100%;">
   <span class="info-box-text">Add Coach</span>
  </div>
  <!-- /.info-box-content -->
 </div>
 <!-- /.info-box -->
</div>


<!-- Delete Modal -->
<div class="modal fade" id="deleteCoachModal" tabindex="-1" role="dialog"
	aria-labelledby="myModalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"
					aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="myModalLabel">Are you sure you want
					to Delete the student Record ?</h4>
			</div>
			<div class="modal-body">
				<div class="modal-footer">
					<button type="button" class="btn btn-default" id="yesDelCoach"
						data-dismiss="modal">Yes</button>
					<button type="button" class="btn btn-primary" id="noDelCoach" name="no"
						data-dismiss="modal">No</button>
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Add School Modal -->
<div class="modal fade modal-wide" id="addCoachModal" tabindex="-1" role="dialog"
 aria-labelledby="myModalLabel">
 <div class="modal-dialog" role="document">
  <div class="modal-content">
   <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"
     aria-label="Close">
     <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title" id="myModalLabel">Add New Coach</h4>
   </div>
   <div class="modal-body">
    
    <form role="form"  id="Coach" method="POST" action="{% url 'addCoach' %}">
    <input type="hidden" name="action_type" id="action_type" value="add"/>
    <input type="hidden" name="coach_id" id="coach_id" value=""/>
    <input type="hidden" name="address_id" id="address_id" value=""/>
    {% csrf_token %} 
    
     <!-- {{ AddressFormSet.management_form }} -->
     <!-- text input -->
     <div id="loadForm">
	     <div class="container">
				<div class="col-lg-12">
					<div class="row">
							
								<div class="col-sm-12">
									<div class="row">
										<div class="col-sm-3 form-group">
											  <label>First Name</label>
											   {{coachform.first_name}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Middle Name</label>
											   {{coachform.middle_name}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Last Name</label>
											   {{coachform.last_name}}
										</div>
										
									</div>
									
									<div class="row">
									<div class="col-sm-3 form-group">
											  <label>Gender</label>
											   {{coachform.gender}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Date Of Birth</label>
											   {{coachform.date_of_birth}}		   								
										</div>
										<div class="col-sm-3 form-group">
											  <label>Email Id</label>
											   {{coachform.email_id}}		   								
										</div>
									</div>
									
									<div class="row">
									<div class="col-sm-3 form-group">
											  <label>Sports</label>
											   {{coachform.sports}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Contact Number</label>
											   {{coachform.contact_no}}
										</div>
										
										<div class="col-sm-3 form-group">
											  <label>Total Yr. Experience</label>
											   {{coachform.total_yrs_exp}}
										</div>
										
									</div>
									
									<div class="row">
									<div class="col-sm-3 form-group">
											  <label>Sequrity Question</label>
											   {{coachform.sec_ques}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Sequrity Answer</label>
											   {{coachform.sec_ans1}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Academy</label>
											   {{coachform.acd_reg}}
										</div>
									</div>
									
									
									<div class="row form-group">
										<label> Permanant Address :</label>
									</div>
									<div class="row">
										<div class="col-sm-3 form-group">
											  <label>Street Number 1</label>
											   {{addressform.street1}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Street Number 2</label>
											   {{addressform.street2}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Zipcode</label>
											   {{addressform.zipcode}}
										</div>
									</div>
									
									<div class="row">
										<div class="col-sm-3 form-group">
											  <label>City</label>
											   {{addressform.city}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Province</label>
											   {{addressform.province}}
										</div>
										<div class="col-sm-3 form-group">
											  <label>Country</label>
											   {{addressform.country}}
										</div>
									</div>
															
							</div>
							
					</div>
				</div>
			</div>	     
     </div>
     <div class="modal-footer">
      <button type="button" class="btn btn-default" id="idClose" data-dismiss="modal">Close</button>
      <button type="button" class="btn btn-default" id="saveStudBtn"  name="save" data-dismiss="modal">save</button>
     </div>
    </form> 
  </div>

  </div>
 </div>
</div>


<!-- Main content -->
<section class="content">
 <div class="row">
  <div class="col-xs-12">
   <div class="box">
    <div class="box-header">
     <h3 class="box-title">List of Coach</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">{%render_table CoachList%}</div>
    <!-- /.box-body -->
   </div>
   <!-- /.box -->
  </div>
  <!-- /.col -->
 </div>
 <!-- /.row -->
</section>

sportsadmin/templates/sportsadmin/exception.html
<div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Kindly Try Later
          </h1>
        </section>

        <!-- Main content -->
        <section class="content">

          <div class="error-page">
            <h2 class="headline text-red">500</h2>
            <div class="error-content">
              <h3><i class="fa fa-warning text-red"></i> Oops! Something went wrong.</h3>
              <p>
                We will work on fixing that right away.
                Meanwhile, you may 	return to dashboard</a> or try using the search form.
              </p>
              <form class="search-form">
                <div class="input-group">
                  <input type="text" name="search" class="form-control" placeholder="Search">
                  <div class="input-group-btn">
                    <button type="submit" name="submit" class="btn btn-danger btn-flat"><i class="fa fa-search"></i></button>
                  </div>
                </div><!-- /.input-group -->
              </form>
            </div>
          </div><!-- /.error-page -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->